# Generated by Django 4.2.2 on 2023-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=128)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.CharField(choices=[('Em analise', 'Em Analise'), ('Negado', 'Negado'), ('Aprovado', 'Aprovado')], default='Em analise', max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
